export const MATCH_CHAT_MESSAGE = 'MATCH_CHAT_MESSAGE';
export const LOBBY_CHAT_MESSAGE = 'LOBBY_CHAT_MESSAGE';
export const FRIEND_CHAT_MESSAGE = 'FRIEND_CHAT_MESSAGE';
export const PRIVATE_MATCH_CHAT_MESSAGE = 'PRIVATE_MATCH_CHAT_MESSAGE';

