export const PUBLIC_USER_STATUS_OFFLINE = 'OFFLINE';
export const PUBLIC_USER_STATUS_ONLINE = 'ONLINE';
export const PUBLIC_USER_STATUS_IN_LOBBY = 'IN_LOBBY';
export const PUBLIC_USER_STATUS_IN_MATCH = 'IN_MATCH';
export const PUBLIC_USER_STATUS_IN_PRIVATE_MATCH = 'IN_PRIVATE_MATCH_LOBBY';
export const PUBLIC_USER_STATUS_UPDATE = 'FRIEND_STATUS_UPDATE';
export const PUBLIC_USER_STATUS_PENDING_ACCEPT_MATCHMAKING = 'PENDING_ACCEPT_MATCHMAKING';
export const FRIEND_ADDED = 'FRIEND_ADDED';
export const FRIEND_DELETED = 'FRIEND_DELETED';

// export const PUBLIC_USER_STATUS_STREAMING = 'STREAMING';

export const PUBLIC_USER_STATUS_TEXT = {
  [PUBLIC_USER_STATUS_OFFLINE]: 'Offline',
  [PUBLIC_USER_STATUS_ONLINE]: 'Online',
  [PUBLIC_USER_STATUS_IN_LOBBY]: 'In a GAME lobby',
  [PUBLIC_USER_STATUS_IN_MATCH]: 'In match playing GAME',
  [PUBLIC_USER_STATUS_IN_PRIVATE_MATCH]: 'In a GAME private match',
  [PUBLIC_USER_STATUS_PENDING_ACCEPT_MATCHMAKING]: 'Pending accept matchmaking'
};
