export const STATUS_IN_LOBBY = 'IN_ROOM_LOBBY_STATUS';
export const STATUS_CONFIRMED_CHALLENGE = 'CONFIRMED_CHALLENGE_STATUS';
export const STATUS_PENDING_CONFIRM_CHALLENGE =
  'PENDING_CONFIRM_CHALLENGE_STATUS';

export const LB_MESSAGE_USER_LEFT = 'LOBBY_USER_LEFT';
export const LB_MESSAGE_USER_JOINED = 'LOBBY_USER_JOIN';
export const LB_MESSAGE_USER_KICKED = 'LOBBY_USER_KICKED';
export const LB_MESSAGE_INCOMING_CHALLENGE = 'INCOMING_LOBBY_CHALLENGE';
export const LB_MESSAGE_LOBBY_CHALLENGED = 'LOBBY_CHALLENGED';
export const LB_MESSAGE_LOBBY_DELETED = 'LOBBY_DELETED';
export const LB_MESSAGE_CHALLENGE_DELETED = 'LOBBY_CHALLENGE_DELETED';
export const LB_MESSAGE_CHALLENGE_REJECTED = 'LOBBY_CHALLENGE_REJECTED';
export const LB_MESSAGE_CHALLENGE_TIMEOUT = 'LOBBY_CHALLENGE_TIMEOUT';
export const LB_MESSAGE_CHALLENGE_MATCH_REJECTED =
'LOBBY_CHALLENGE_MATCH_NOT_ACCEPTED';
export const LB_MESSAGE_LOBBY_EXPIRED = 'LOBBY_EXPIRED';
