export const STATUS_MM_FINDING_MATCH = 'FINDING_MATCHMAKING_MATCH_STATUS';
// REFINDING status does not exist on backend;
export const STATUS_MM_REFINDING_MATCH = 'REFINDING_MATCHMAKING_MATCH_STATUS';
export const STATUS_MM_PENDING_ACCEPT =
  'PENDING_ACCEPT_MATCHMAKING_MATCH_STATUS';
export const STATUS_MM_MATCH_ACCEPTED = 'ACCEPTED_MATCHMAKING_MATCH_STATUS';
export const STATUS_MM_MATCH_REJECTED = 'MATCHMAKING_MATCH_REJECTED';

export const MM_MESSAGE_FIND_CANCELED = 'MATCHMAKING_FIND_CANCELED';
