export const STATUS_MATCH_IN_PROGRESS = 'MATCH_IN_PROGRESS_STATUS';

export const MATCH_STATUS_SCORE_CONFIRMED = 'SCORE_CONFIRMED';
export const MATCH_STATUS_SCORE_REPORTED = 'SCORE_REPORTED';
export const MATCH_STATUS_ISSUE_REPORTED = 'ISSUE_REPORTED';
export const MATCH_STATUS_WIN_RESULT = 'MATCH_WIN_RESULT';
export const MATCH_STATUS_LOST_RESULT = 'MATCH_LOST_RESULT';
export const MATCH_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const MATCH_STATUS_RESOLVED = 'RESOLVED';
export const MATCH_STATUS_DISPUTED = 'IN_DISPUTE';
export const MATCH_STATUS_CANCELED = 'CANCELED';
export const MATCH_STATUS_SCHEDULED = 'SCHEDULED';
export const MATCH_STATUS_PENDING_HOST_CHECKIN = 'PENDING_HOST_CHECKIN';
export const MATCH_STATUS_PENDING_MEMBER_CHECKIN = 'PENDING_MEMBER_CHECKIN';
export const MATCH_STATUS_CANCELED_PLAYER_CHECKIN_AFK = 'MATCH_CANCELED_PLAYER_CHECKIN_AFK';
export const MATCH_STATUS_CANCELED_HOST_CHECKIN_AFK = 'MATCH_CANCELED_HOST_CHECKIN_AFK';
export const MATCH_STATUS_REFEREE_CALLED = 'MATCH_REFEREE_CALLED';
export const MATCH_STATUS_REFEREE_CALL_RESOLVED = 'MATCH_REFEREE_CALL_RESOLVED';
export const MATCH_STATUS_PAUSED = 'PAUSED';
export const MATCH_STATUS_CANCELED_PLAYER_CHECKIN_AFK_RAW = 'CANCELED_PLAYER_CHECKIN_AFK';
export const MATCH_STATUS_CANCELED_HOST_CHECKIN_AFK_RAW = 'CANCELED_HOST_CHECKIN_AFK';
export const MATCH_CREATION_ERROR = 'MATCH_CREATION_ERROR';

export const REMATCH_OFFER = 'REMATCH_OFFER';
export const REMATCH_REJECT = 'REMATCH_REJECT';

// export const MATCH_FEE_PERCENT = 0.10;
export const MATCH_FEE_PERCENT = 0.04;

export const MATCH_STATUS_TEXT_BY_CODE = {
  [MATCH_STATUS_SCHEDULED]: 'schedule_matches.match_scheduled',
  [MATCH_STATUS_IN_PROGRESS]: 'match_in_progress',
  [MATCH_STATUS_SCORE_REPORTED]: 'match_score_uploaded',
  [MATCH_STATUS_DISPUTED]: 'match_in_dispute',
  [MATCH_STATUS_RESOLVED]: 'match_finished',
  [MATCH_STATUS_CANCELED]: 'match_canceled',
  [MATCH_STATUS_PAUSED]: 'match_paused',
  [MATCH_STATUS_PENDING_HOST_CHECKIN]: 'match_creation',
  [MATCH_STATUS_PENDING_MEMBER_CHECKIN]: 'match_creation'
};

export const MATCH_STREAM_STATUS_UPDATE = 'STREAM_STATUS_UPDATE';
