export const PARTY_USER_JOINED = 'PARTY_USER_JOIN';
export const PARTY_USER_LEFT = 'PARTY_USER_LEFT';
export const PARTY_JOIN_LOBBY = 'LOBBY_PARTY_JOIN';
export const PARTY_JOIN_PRIVATE_MATCH =
  'PRIVATE_MATCH_LOBBY_PARTY_JOIN_FREE_MEMBERS';

export const PARTY_CHAT_MESSAGE = 'PARTY_CHAT_MESSAGE';
