export const IN_PRIVATE_MATCH_LOBBY_STATUS = 'IN_PRIVATE_MATCH_LOBBY_STATUS';
export const PM_STATUS_MATCH_STARTING = 'PRIVATE_MATCH_STARTING';

export const PM_MESSAGE_LOBBY_DELETED = 'PRIVATE_MATCH_LOBBY_DELETED';
export const PM_MESSAGE_USER_LEFT = 'PRIVATE_MATCH_LOBBY_USER_LEFT';
export const PM_MESSAGE_USER_JOINED =
  'PRIVATE_MATCH_LOBBY_USER_JOIN_FREE_MEMBERS';
export const PM_MESSAGE_USER_MOVED =
  'PRIVATE_MATCH_LOBBY_USER_MOVED_FREE_MEMBERS';
export const PM_MESSAGE_HOST_TEAM_USER_JOINED =
  'PRIVATE_MATCH_LOBBY_USER_JOIN_HOST_TEAM';
export const PM_MESSAGE_GUEST_TEAM_USER_JOINED =
  'PRIVATE_MATCH_LOBBY_USER_JOIN_GUEST_TEAM';
export const PM_MESSAGE_MATCH_STARTING = 'PRIVATE_MATCH_LOBBY_MATCH_STARTING';
export const PM_MESSAGE_USER_KICKED = 'PRIVATE_MATCH_LOBBY_USER_KICKED';
