export const TOURNAMENT_MATCH_STATUS_PENDING = 'TOURNAMENT_MATCH_STATUS_PENDING';
export const TOURNAMENT_MATCH_STATUS_IN_PROGRESS = 'TOURNAMENT_MATCH_STATUS_IN_PROGRESS';
export const TOURNAMENT_MATCH_STATUS_FINISHED = 'TOURNAMENT_MATCH_STATUS_FINISHED';
export const TOURNAMENT_MATCH_STATUS_EMPTY_OPPONENT = 'TOURNAMENT_MATCH_STATUS_EMPTY_OPPONENT';
export const TOURNAMENT_STATUS_OPEN_SIGNUP = 'TOURNAMENT_STATUS_OPEN_SIGNUP';
