export const IDENTITY_VERIFICATION_STATUS_UPDATE = 'IDENTITY_VERIFICATION_STATUS_UPDATE';
export const IDENTITY_VERIFICATION_DECISION = 'IDENTITY_VERIFICATION_DECISION';

export const IDENTITY_VERIFICATION_APPROVED = 9001;
export const IDENTITY_VERIFICATION_DENIED = 9102;