export const CURRENCIES = {
  USD: 'USD',
  DUELME_COINS: 'DUELME_COINS',
};

export const CURRENCY_LABELS = {};
CURRENCY_LABELS[CURRENCIES.USD] = 'USD';
CURRENCY_LABELS[CURRENCIES.DUELME_COINS] = 'DubbzCoins';

export const CURRENCY_SYMBOLS = {};
CURRENCY_SYMBOLS[CURRENCIES.USD] = '$';
CURRENCY_SYMBOLS[CURRENCIES.DUELME_COINS] = 'Ð';

export const CURRENCY_SELECT_OPTIONS = [
  { value: CURRENCIES.USD, display: 'USD' },
  { value: CURRENCIES.DUELME_COINS, display: 'DubbzCoins' },
];

export const TRANSACTION_MATCH_LOST = 'TRANSACTION_TYPE_MATCH_LOSE';
export const TRANSACTION_MATCH_WON = 'TRANSACTION_TYPE_MATCH_WIN';
export const TRANSACTION_TYPE_FOUNDS_ADDED = 'TRANSACTION_TYPE_FOUNDS_ADDED';
export const TRANSACTION_TYPE_FOUNDS_ADDED_ADMIN = 'TRANSACTION_TYPE_FOUNDS_ADDED_ADMIN';
export const TRANSACTION_TYPE_FOUNDS_ADDED_IN_PROGRESS = 'TRANSACTION_TYPE_FOUNDS_ADDED_IN_PROGRESS';
export const TRANSACTION_TYPE_FOUNDS_ADDED_REFERRED = 'TRANSACTION_TYPE_FOUNDS_ADDED_REFERRED';
export const TRANSACTION_TYPE_BONUS_ADDED = 'TRANSACTION_TYPE_BONUS_ADDED';
export const TRANSACTION_TYPE_FOUNDS_ADDED_PENALIZATION = 'TRANSACTION_TYPE_FOUNDS_ADDED_PENALIZATION';
export const TRANSACTION_TYPE_FOUNDS_SUBTRACTED = 'TRANSACTION_TYPE_FOUNDS_SUBTRACTED';
export const TRANSACTION_TYPE_FOUNDS_SUBTRACTED_PENALIZATION = 'TRANSACTION_TYPE_FOUNDS_SUBTRACTED_PENALIZATION';
export const TRANSACTION_TYPE_FOUNDS_SUBTRACTED_ADMIN = 'TRANSACTION_TYPE_FOUNDS_SUBTRACTED_ADMIN';
export const TRANSACTION_TYPE_MATCH_ENTRY_FEE = 'TRANSACTION_TYPE_MATCH_ENTRY_FEE';
export const TRANSACTION_TYPE_SCHEDULE_MATCH_ENTRY_FEE = 'TRANSACTION_TYPE_SCHEDULE_MATCH_ENTRY_FEE';
export const TRANSACTION_TYPE_SCHEDULE_MATCH_ENTRY_FEE_RETURNED = 'TRANSACTION_TYPE_SCHEDULE_MATCH_ENTRY_FEE_RETURNED';
export const TRANSACTION_TYPE_MATCH_ENTRY_FEE_RETURNED = 'TRANSACTION_TYPE_MATCH_ENTRY_FEE_RETURNED';
export const EXPIRED = 'EXPIRED';
export const UNRESOLVED_GENERIC = 'UNRESOLVED_GENERIC';
export const UNRESOLVED_UNDERPAID = 'UNRESOLVED_UNDERPAID';
export const REFUNDED = 'REFUNDED';
export const WALLET_UPDATED = 'WALLET_UPDATED';
